// This file will be generated by: npx supabase gen types typescript --project-id your_project_id
// For now, we'll use a placeholder type
export type Database = {
  public: {
    Tables: {
      profiles: {
        Row: {
          id: string
          username: string | null
          full_name: string | null
          avatar_url: string | null
          created_at: string
          updated_at: string
        }
        Insert: {
          id: string
          username?: string | null
          full_name?: string | null
          avatar_url?: string | null
          created_at?: string
          updated_at?: string
        }
        Update: {
          id?: string
          username?: string | null
          full_name?: string | null
          avatar_url?: string | null
          created_at?: string
          updated_at?: string
        }
      }
      stacks: {
        Row: {
          id: string
          owner_id: string
          name: string
          description: string | null
          is_public: boolean
          published_at: string | null
          settings: any
          created_at: string
          updated_at: string
        }
        Insert: {
          id?: string
          owner_id: string
          name: string
          description?: string | null
          is_public?: boolean
          published_at?: string | null
          settings?: any
          created_at?: string
          updated_at?: string
        }
        Update: {
          id?: string
          owner_id?: string
          name?: string
          description?: string | null
          is_public?: boolean
          published_at?: string | null
          settings?: any
          created_at?: string
          updated_at?: string
        }
      }
      cards: {
        Row: {
          id: string
          stack_id: string
          name: string
          order_index: number
          background_color: string
          background_image: string | null
          script: string | null
          created_at: string
          updated_at: string
        }
        Insert: {
          id?: string
          stack_id: string
          name?: string
          order_index?: number
          background_color?: string
          background_image?: string | null
          script?: string | null
          created_at?: string
          updated_at?: string
        }
        Update: {
          id?: string
          stack_id?: string
          name?: string
          order_index?: number
          background_color?: string
          background_image?: string | null
          script?: string | null
          created_at?: string
          updated_at?: string
        }
      }
      elements: {
        Row: {
          id: string
          card_id: string
          type: string
          order_index: number
          position: any
          properties: any
          script: string | null
          created_at: string
          updated_at: string
        }
        Insert: {
          id?: string
          card_id: string
          type: string
          order_index?: number
          position?: any
          properties?: any
          script?: string | null
          created_at?: string
          updated_at?: string
        }
        Update: {
          id?: string
          card_id?: string
          type?: string
          order_index?: number
          position?: any
          properties?: any
          script?: string | null
          created_at?: string
          updated_at?: string
        }
      }
      assets: {
        Row: {
          id: string
          stack_id: string
          type: string
          filename: string
          url: string
          size: number | null
          mime_type: string | null
          uploaded_at: string
        }
        Insert: {
          id?: string
          stack_id: string
          type: string
          filename: string
          url: string
          size?: number | null
          mime_type?: string | null
          uploaded_at?: string
        }
        Update: {
          id?: string
          stack_id?: string
          type?: string
          filename?: string
          url?: string
          size?: number | null
          mime_type?: string | null
          uploaded_at?: string
        }
      }
    }
  }
}
