'use client'

import { Download, FileJson, FileText } from 'lucide-react'
import { Button } from '@/components/ui/button'
import type { AnalyticsReport } from '../lib/types'

interface ExportButtonProps {
  report: AnalyticsReport | null
  disabled?: boolean
}

export function ExportButton({ report, disabled }: ExportButtonProps) {
  const handleExportJSON = () => {
    if (!report) return

    const blob = new Blob([JSON.stringify(report, null, 2)], {
      type: 'application/json',
    })
    const url = URL.createObjectURL(blob)
    const a = document.createElement('a')
    a.href = url
    a.download = `story-analytics-${report.storyId.slice(0, 8)}-${Date.now()}.json`
    document.body.appendChild(a)
    a.click()
    document.body.removeChild(a)
    URL.revokeObjectURL(url)
  }

  const handleExportText = () => {
    if (!report) return

    const lines = [
      `# Story Analytics Report`,
      ``,
      `**Story:** ${report.storyName}`,
      `**Generated:** ${new Date(report.generatedAt).toLocaleString()}`,
      ``,
      `## Summary`,
      ``,
      `- **Paths Simulated:** ${report.summary.totalPathsSimulated}`,
      `- **Completion Rate:** ${report.summary.completionRate}`,
      `- **Average Path Length:** ${report.summary.averagePathLength} cards`,
      `- **Average Completion Time:** ${report.summary.averageCompletionTime}`,
      `- **Total Cards:** ${report.summary.totalCards}`,
      `- **Reachable Cards:** ${report.summary.reachableCards}`,
      `- **Dead-End Cards (Story Endings):** ${report.summary.deadEndCards}`,
      `- **Orphaned Cards:** ${report.summary.orphanedCards}`,
      ``,
      `## Top Paths`,
      ``,
      ...report.topPaths.map(
        (p) => `${p.rank}. ${p.pathSignature} (${p.frequency}x - ${p.percentage})`
      ),
      ``,
      `## Card Metrics`,
      ``,
      `| Card | Visits | Visit Rate | Avg Time | Dead End | Top Choice |`,
      `|------|--------|------------|----------|----------|------------|`,
      ...report.cardMetrics.map(
        (c) =>
          `| ${c.cardTitle} | ${c.visits} | ${c.visitRate} | ${c.averageTime} | ${
            c.isDeadEnd ? 'Yes' : 'No'
          } | ${c.topChoice || '-'} |`
      ),
      ``,
      `---`,
      ``,
      `*Generated by HyperCard Renaissance Story Analyzer*`,
    ]

    const content = lines.join('\n')
    const blob = new Blob([content], { type: 'text/markdown' })
    const url = URL.createObjectURL(blob)
    const a = document.createElement('a')
    a.href = url
    a.download = `story-analytics-${report.storyId.slice(0, 8)}-${Date.now()}.md`
    document.body.appendChild(a)
    a.click()
    document.body.removeChild(a)
    URL.revokeObjectURL(url)
  }

  return (
    <div className="flex items-center gap-1">
      <Button
        onClick={handleExportText}
        disabled={disabled || !report}
        size="sm"
        variant="outline"
        className="gap-1.5"
        data-testid="export-markdown-btn"
      >
        <FileText className="w-3.5 h-3.5" />
        <span className="hidden sm:inline">Export MD</span>
      </Button>
      <Button
        onClick={handleExportJSON}
        disabled={disabled || !report}
        size="sm"
        variant="outline"
        className="gap-1.5"
        data-testid="export-json-btn"
      >
        <FileJson className="w-3.5 h-3.5" />
        <span className="hidden sm:inline">Export JSON</span>
      </Button>
    </div>
  )
}
